# <span style="color:#0b486b">  FIT3181: Deep Learning (2021)</span>
***
*CE/Lecturer:* Dr **Trung Le** | trunglm@monash.edu <br/>
*Head Tutor:* Mr **Thanh Nguyen** | thanh.nguyen4@monash.edu <br/>
<br/>
Department of Data Science and AI, Faculty of Information Technology, Monash University, Australia
***

# <span style="color:#0b486b">  Student Information</span>
***
Surname: **Haw**  <br/>
Firstname: **Xiao Ying**    <br/>
Student ID: **29797918**    <br/>
Email: **xhaw0001@student.monash.edu**    <br/>
Your tutorial time: **Tuesday 3.00p.m.-5.00p.m.**    <br/>
***

## <span style="color:#0b486b">Part 1: Theory and Knowledge Questions</span>
<div style="text-align: right"><span style="color:red; font-weight:bold">[Total marks for this part: 30 points]<span></div>

####  <span style="color:red">**Question 1.1**</span> **Activation function plays an important role in modern Deep NNs. For each of the activation function below, state its output range and find its derivative (show your steps)**

<span style="color:red">**(a)**</span> Sigmoid: $\sigma(x) = \frac{1}{1+\text{exp}{(-x)}}$ 
<div style="text-align: right"><span style="color:red">[1.5 points]</span></div> 

<span style="color:red">**(b)**</span> Tanh: $\sigma(x) = \frac{\exp(x) - \exp{(-x)}}{\exp(x) + \exp{(-x)}}= \frac{1-\exp(-2x)}{1+\exp(-2x)}$
<div style="text-align: right"><span style="color:red">[1.5 points]</span></div> 

<span style="color:orange">**Answer for Question 1.1**</span> <br/>
<span style="color:orange">**(a)**</span> Sigmoid: $\sigma'(x) = \sigma(x)(1-\sigma(x))$, output range is 0 to 1 <br/>
<span style="color:orange">**(b)**</span> Tanh: $\sigma'(x) = 1-\sigma^{2}(x)$, output range is -1 to 1

***
####  <span style="color:red">**Question 1.2**</span> **Softmax activation aims to transform discriminative values to prediction probabilities. Consider a classification task with $M=4$ classes and a data example $x$ with a ground-truth label $y=2$. Assume that at the output layer of a feed-forward neural network, we obtain the logits $h^{L}=[2,-1,5,0]$.**
<span style="color:red">**(a)**</span>  What is the corresonding prediction probabilities $p(x)$?
<div style="text-align: right"><span style="color:red">[1.5 points]</span></div> 

<span style="color:red">**(b)**</span>  What is the cross-entropy loss caused by the feed-forward neural network at $(x,y)$?
<div style="text-align: right"><span style="color:red">[1.5 points]</span></div> 

**You need to show both formulas and numerical results for earning full mark. Although it is optional, it is great if you show your numpy code for your computation.**

<span style="color:orange">**Answer for Question 1.2**</span> <br/>
<span style="color:orange">**(a)**</span> Formula: $ p_i=\left[ \frac{exp(h_m)}{\sum_{i=1}^{M}exp(h_i)} \right] ^{M}_{m=1} $ <br/> <br/>
$ p_1 = \frac{\exp(2)}{\exp(2) + \exp(-1) + \exp(5) + \exp(0)} \approx 0.0470, $ <br/>
$ p_2 = \frac{\exp(-1)}{\exp(2) + \exp(-1) + \exp(5) + \exp(0)} \approx 0.0023, $ <br/>
$ p_3 = \frac{\exp(5)}{\exp(2) + \exp(-1) + \exp(5) + \exp(0)} \approx 0.9443, $ <br/>
$ p_4 = \frac{\exp(0)}{\exp(2) + \exp(-1) + \exp(5) + \exp(0)} \approx 0.0064 $ <br/>
<br/>

<span style="color:orange">**(b)**</span> After softmax activation function, $ p=[0.0470, 0.0023, 0.9443, 0.0064] $. <br/><br/>
$ Formula: CE(y,p) = - \sum^{M}_{m=1}y_mlogp_m $ <br/> <br/>
$ l(y,p) = CE([0,1,0,0][0.0470, 0.0023, 0.9443, 0.0064]) = -(0)(log0.0470) - (1)(log0.0023) - (0)(log0.9443) - (0)(log0.0064) = - log0.0023 $ <br/><br/>
Cross-entropy loss caused by the feed-forward neural network at (𝑥,𝑦) is 6.0748.

***
####  <span style="color:red">**Question 1.3**</span> **Linear operation and element-wise activation are two building-blocks for conducting a layer in a feedforward neural network.**

<span style="color:red">**(a)**</span> Assume that hidden layer $1$ has value $h^1(x)= \left[\begin{array}{ccc}
1.5 & 2.0 \end{array}\right]^T$ and the weight matrix and bias at the second layer are:
- $W^{2}=\left[\begin{array}{cc}
-1 & -1\\
-1 & 1\\
-1 & 0
\end{array}\right]$.
What is the value of the hidden layer $\bar{h}^{2}(x)$ after applying *the linear operation* with the matrix $W^2$ and the bias $b^2$ over $h^1$.

<div style="text-align: right"><span style="color:red">[2 points]</span></div> 


<span style="color:red">**(b)**</span> Assume that we apply *the ReLU activation function* at the second layer. What is the value of the hidden layer $h^2(x)$ after we apply the activation function?

<div style="text-align: right"><span style="color:red">[2 points]</span></div> 

**You need to show both formulas and numerical results for earning full mark. Although it is optional, it is great if you show your numpy code for your computation.**

<span style="color:orange">**Answer for Question 1.3**</span> <br/>
<span style="color:orange">**(a)**</span>
$\bar{h}^{2}(x) = W^2 h^1(x) + b^2$ <br/>
$\bar{h}^{2}(x) = \left[\begin{array}{cc}
-3.5\\
0.5\\
-1.5
\end{array}\right]$<br/><br/>

<span style="color:orange">**(b)**</span> ReLu Activation function: $ReLu(x) = max(0,x)$ <br/>
Therefore, $h^2(x) = \left[\begin{array}{cc}
0\\
0.5\\
0
\end{array}\right]$ <br/><br/>

In [1]:
import numpy as np

In [2]:
# Numpy code for Question 1.3(a)

h1 = np.transpose([[1.5, 2.0]])
w2 = np.array([[-1, -1],
              [-1, 1],
              [-1, 0]])
b2 = np.zeros((3,1))

h2_bar = w2.dot(h1) + b2
h2_bar

array([[-3.5],
       [ 0.5],
       [-1.5]])

In [3]:
# Numpy code for Question 1.3(b)

def relu(x):
    return np.maximum(0,x)

h2 = relu(h2_bar)
h2

array([[0. ],
       [0.5],
       [0. ]])

***
####  <span style="color:red">**Question 1.4**</span> **Assume that we are conducting a multilayered feedforward neural network for a regression problem to predict to real-valued $y_1, y_2$, and $y_3$. The architecture of this network ($3 (Input)\rightarrow4(ReLU)\rightarrow 3(Output)$) is shown in the following figure**:


<img src="Figures/FeedforwardNN.png" width="500" align="center"/>

We now feed a feature vector $x=\left[\begin{array}{ccc}
1.2 & -1 & 2\end{array}\right]^{T}$ with ground-truth label $y=\left[\begin{array}{ccc} 1.5 & -1 & 2\end{array}\right]^{T}$ to the above network. 

**Forward propagation**

<span style="color:red">**(a)**</span>  What is the value of $\bar{h}^{1}(x)$?
<div style="text-align: right"><span style="color:red">[1.5 points]</span></div>

<span style="color:red">**(b)**</span>  What is the value of $h^{1}(x)$?
<div style="text-align: right"><span style="color:red">[1.5 points]</span></div>

<span style="color:red">**(c)**</span>  What is the predicted value $\hat{y}$?
<div style="text-align: right"><span style="color:red">[1.5 points]</span></div>

<span style="color:red">**(d)**</span>  Suppose that we use the L2 loss. What is the value of the L2 loss $l$?
<div style="text-align: right"><span style="color:red">[1.5 points]</span></div>

**Backward propagation**

<span style="color:red">**(e)**</span> What are the derivatives $\frac{\partial l}{\partial h^{2}},\frac{\partial l}{\partial W^{2}}$, and $\frac{\partial l}{\partial b^{2}}$? 
<div style="text-align: right"><span style="color:red">[5 points]</span></div>

<span style="color:red">**(f)**</span> What are the derivatives $\frac{\partial l}{\partial h^{1}}, \frac{\partial l}{\partial \bar{h}^{1}},\frac{\partial l}{\partial W^{1}}$, and $\frac{\partial l}{\partial b^{1}}$? 
<div style="text-align: right"><span style="color:red">[5 points]</span></div>

**SGD update**

<span style="color:red">**(g)**</span> Assume that we use SGD with learning rate $\eta=0.01$ to update the model parameters. What are the values of $W^2, b^2$ and $W^1, b^1$ after updating?
<div style="text-align: right"><span style="color:red">[4 points]</span></div>

**You need to show both formulas and numerical results for earning full mark. Although it is optional, it is great if you show your numpy code for your computation.**

<span style="color:orange">**Answer for Question 1.4**</span> <br/>
<span style="color:orange">**(a)**</span> $\bar{h}^{1}(x) = W^1x + b^1$ <br/>
$\bar{h}^{1}(x) = \left[\begin{array}{cc}
2.2\\
4\\
-0.8\\
1.2
\end{array}\right]$ <br/><br/>

<span style="color:orange">**(b)**</span> $h^1(x) = \sigma(\bar{h}^{1}(x))$ <br/>
$h^1(x) = \left[\begin{array}{cc}
2.2\\
4\\
0\\
1.2
\end{array}\right]$ <br/><br/>

<span style="color:orange">**(c)**</span> $\bar{h}^{2}(x) = W^2h^1(x) + b^2$ <br/>
$\bar{h}^{2}(x) = \left[\begin{array}{cc}
7.1\\
1.2\\
1.1
\end{array}\right]$ <br/><br/>

$\hat{y} = h^2(x) = \sigma(\bar{h}^{2}(x))$ <br/>
$\hat{y} = h^2(x) = \left[\begin{array}{cc}
7.1\\
1.2\\
1.1
\end{array}\right]$ <br/><br/>

<span style="color:orange">**(d)**</span> L2 loss : $l(y,\hat{y}) = l(y,h^2(x))$ <br/>
$l(y,\hat{y}) = \frac{1}{2}[(y_1-h^2_1)^2 + (y_2-h^2_2)^2 + (y_3-h^2_3)^2]$ <br/>
$l(y,\hat{y}) = \frac{1}{2}[(1.5-7.1)^2 + (-1-1.2)^2 + (2-1.1)^2]$ <br/>
$l(y,\hat{y}) = 18.505$
<br/>

<span style="color:orange">**(e)**</span> $\because l=\frac{1}{2}(y-\hat{y})^2$ <br/>
$\therefore\frac{\partial l}{\partial h^{2}} = \frac{\partial}{\partial h^{2}}[\frac{1}{2}(y-\hat{y})^2]$ <br/><br/>
$\because \hat{y} = h^2 $ <br/>
$\therefore \frac{\partial l}{\partial h^{2}} = \frac{\partial}{\partial h^{2}}[\frac{1}{2}(y-h^2)^2]$ <br/>
$\frac{\partial l}{\partial h^{2}} = \frac{2(y-h^2)(0-1)}{2} = h^2-y$ <br/>
$\frac{\partial l}{\partial h^{2}} = \left[\begin{array}{cc}
5.6\\
2.2\\ 
-0.9
\end{array}\right]^T = \left[\begin{array}{cc} 5.6 & 2.2 & -0.9 \end{array}\right]$ <br/>

We know that $h^2 = W^2h^1+b^2$, so <br/>
$\frac{\partial h^2}{\partial W^2} = \frac{\partial}{\partial W^2}[W^2h^1+b^2]$ ; $\frac{\partial h^2}{\partial b^2} = \frac{\partial}{\partial b^2}[W^2h^1+b^2]$ <br/>
After derivation, $\frac{\partial h^2}{\partial W^2} = h^1$ ; $\frac{\partial h^2}{\partial b^2} = 1$ and let $g^2 = \frac{\partial l}{\partial h^2}.$ <br/><br/>
$\frac{\partial l}{\partial W^2} = \frac{\partial l}{\partial h^2} \times \frac{\partial h^2}{\partial W^2}$ <br/>
$\frac{\partial l}{\partial W^2} = (g^2)^T \times (h^1)^T$<br/>
$\frac{\partial l}{\partial W^2} = \left[\begin{array}{cc}
12.32 & 22.4 & 0 & 6.72\\
4.84 & 8.8 & 0 & 2.64\\
-1.98 & -3.6 & 0 & -1.08
\end{array}\right]$ <br/>

$\frac{\partial l}{\partial b^2} = \frac{\partial l}{\partial h^2} \times \frac{\partial h^2}{\partial b^2}$ <br/>
$\frac{\partial l}{\partial b^2} = g^2$ <br/>
$\frac{\partial l}{\partial b^2} = \left[\begin{array}{cc} 5.6 & 2.2 & -0.9 \end{array}\right]^T = \left[\begin{array}{cc}
5.6\\
2.2\\
-0.9
\end{array}\right]$ <br/>


<span style="color:orange">**(f)**</span> 
We know that $h^2 = W^2h^1+b^2$, so $\frac{\partial h^2}{\partial h^1} = \frac{\partial}{\partial h^1}[W^2h^1+b^2]$. <br/>
After derivation, $\frac{\partial h^2}{\partial h^1} = W^2$. <br/><br/>
$\frac{\partial l}{\partial h^{1}} = \frac{\partial l}{\partial h^{2}} \times \frac{\partial h^{2}}{\partial h^{1}}$ <br/>
$\frac{\partial l}{\partial h^{1}} = g^2W^2$ <br/>
$\frac{\partial l}{\partial h^{1}} = \left[\begin{array}{cc} 9.3 & 4.7 & 6.9 & -2.5 \end{array}\right]$ <br/><br/>

Let $\frac{\partial l}{\partial h^{1}}$ be $g^1$.<br/>
$\frac{\partial l}{\partial \bar{h}^{1}} = \frac{\partial l}{\partial h^{1}} \times \frac{\partial h^{1}}{\partial \bar{h}^{1}}$ <br/>
$\frac{\partial l}{\partial \bar{h}^{1}} = g^1diag(\sigma'(\bar{h}^{1}))$ <br/>
$\frac{\partial l}{\partial \bar{h}^{1}} = \left[\begin{array}{cc} 9.3 & 4.7 & 6.9 & -2.5 \end{array}\right] \times \left[\begin{array}{cc} 1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 0 & 0 \\ 0 & 0 & 0 & 1\end{array}\right]$ <br/>
$\frac{\partial l}{\partial \bar{h}^{1}} = \left[\begin{array}{cc} 9.3 & 4.7 & 0 & -2.5 \end{array}\right]$ <br/>

$\bar{h}^{1} = W^1x+b^1$, therefore <br/>
$\frac{\partial \bar{h}^{1}}{\partial W^{1}} = \frac{\partial}{\partial W^{1}}[W^1x+b^1] = x$ ; <br/>
$\frac{\partial \bar{h}^{1}}{\partial b^{1}} = \frac{\partial}{\partial b^{1}}[W^1x+b^1] = 1$ ; <br/>
and let $\frac{\partial l}{\partial \bar{h}^{1}}$ be $\bar{g}^{1}$ <br/><br/>
$\frac{\partial l}{\partial W^{1}} = \frac{\partial l}{\partial \bar{h}^{1}} \times \frac{\partial \bar{h}^{1}}{\partial W^{1}}$ <br/>
$\frac{\partial l}{\partial W^{1}} = (\bar{g}^{1})^T(h^0)^T$ <br/>
$\frac{\partial l}{\partial W^{1}} = \left[\begin{array}{cc}
11.16 & -9.3 & 18.6 \\
5.64 & -4.7 & 9.4 \\
0 & 0 & 0 \\
-3 & 2.5 & -5
\end{array}\right]$ <br/><br/>

$\frac{\partial l}{\partial b^{1}} = \frac{\partial l}{\partial \bar{h}^{1}} \times \frac{\partial \bar{h}^{1}}{\partial b^{1}}$ <br/>
$\frac{\partial l}{\partial b^{1}} = \bar{g}^{1}$ <br/>
$\frac{\partial l}{\partial b^{1}} = \left[\begin{array}{cc} 9.3 & 4.7 & 0 & -2.5 \end{array}\right]^T = \left[\begin{array}{cc} 9.3 \\ 4.7 \\ 0 \\ -2.5 \end{array}\right]$ <br/><br/>

<span style="color:orange">**(g)**</span> $W^2 = W^2 - \eta \frac{\partial l}{\partial W^2}$ <br/>
$W^2 = \left[\begin{array}{cc}
1.3768 & 0.776 & 1 & -1.0672\\
-0.0484 & -0.088 & 1 & 0.9736\\
-0.9802 & 1.036 & 1 & -0.9892 \end{array}\right]$ after SGD update. <br/><br/>

$b^2 = b^2 - \eta \frac{\partial l}{\partial b^2}$ <br/>
$b^2 = \left[\begin{array}{cc} 0.944 \\ -0.022 \\ 0.509 \end{array}\right]$ after SGD update.<br/><br/>

$W^1 = W^1 - \eta \frac{\partial l}{\partial W^1}$ <br/>
$W^1 = \left[\begin{array}{cc}
0.8884 & -0.907 & 0.186\\
-0.0564 & -0.953 & 0.906\\
1 & 1 & -1\\
1.03 & 0.975 & 1.05\end{array}\right]$ after SGD update.<br/><br/>

$b^1 = b^1 - \eta \frac{\partial l}{\partial b^1}$ <br/><br/>
$b^1 = \left[\begin{array}{cc} -0.093 \\ 0.953 \\ 1 \\ -0.975 \end{array}\right]$ after SGD update.<br/><br/>

In [4]:
# Numpy code for Question 1.4

x = np.array([[1.2],
             [-1],
             [2]])

y = np.array([[1.5],
             [-1],
             [2]])

w1 = np.array([[1,-1,0],
              [0,-1,1],
              [1,1,-1],
              [1,1,1]])

b1 = np.array([[0],
              [1],
              [1],
              [-1]])

w2 = np.array([[1.5,1,1,-1],
              [0,0,1,1],
              [-1,1,1,-1]])

b2 = np.array([[1],
              [0],
              [0.5]])

h1_bar = w1.dot(x) + b1
print("h1_bar:\n", h1_bar)

h1 = relu(h1_bar)
print("\nh1:\n", h1)

h2 = w2.dot(h1) + b2
print("\nh2:\n", h2)

loss = 0.5 * (y-h2_bar)**2
print("\nL2 loss:\n", loss)

g2 = np.transpose(h2-y)
print("\ng2:\n",g2)

derivativeW2 = np.transpose(g2).dot(np.transpose(h1))
print("\nderivativeW2:\n",derivativeW2)

g1 = (g2).dot(w2)
print("\ng1:",g1)

D = np.array([[1,0,0,0],
             [0,1,0,0],
             [0,0,0,0],
             [0,0,0,1]])
g1bar = g1.dot(D)
print("\ng1bar:\n",g1bar)

derivativeW1 = np.transpose(g1bar).dot(np.transpose(x))
print("\nderivativeW1:\n",derivativeW1)

sgdw2 = w2 - 0.01*derivativeW2
print("\nsgdw2:\n", sgdw2)

sgdb2 = b2 - 0.01*np.transpose(g2)
print("\nsgdb2:\n", sgdb2)

sgdw1 = w1 - 0.01*derivativeW1
print("\nsgdw1:\n", sgdw1)

sgdb1 = b1 - 0.01*np.transpose(g1bar)
print("\nsgdb1:\n", sgdb1)

h1_bar:
 [[ 2.2]
 [ 4. ]
 [-0.8]
 [ 1.2]]

h1:
 [[2.2]
 [4. ]
 [0. ]
 [1.2]]

h2:
 [[7.1]
 [1.2]
 [1.1]]

L2 loss:
 [[12.5  ]
 [ 1.125]
 [ 6.125]]

g2:
 [[ 5.6  2.2 -0.9]]

derivativeW2:
 [[12.32 22.4   0.    6.72]
 [ 4.84  8.8   0.    2.64]
 [-1.98 -3.6  -0.   -1.08]]

g1: [[ 9.3  4.7  6.9 -2.5]]

g1bar:
 [[ 9.3  4.7  0.  -2.5]]

derivativeW1:
 [[11.16 -9.3  18.6 ]
 [ 5.64 -4.7   9.4 ]
 [ 0.   -0.    0.  ]
 [-3.    2.5  -5.  ]]

sgdw2:
 [[ 1.3768  0.776   1.     -1.0672]
 [-0.0484 -0.088   1.      0.9736]
 [-0.9802  1.036   1.     -0.9892]]

sgdb2:
 [[ 0.944]
 [-0.022]
 [ 0.509]]

sgdw1:
 [[ 0.8884 -0.907  -0.186 ]
 [-0.0564 -0.953   0.906 ]
 [ 1.      1.     -1.    ]
 [ 1.03    0.975   1.05  ]]

sgdb1:
 [[-0.093]
 [ 0.953]
 [ 1.   ]
 [-0.975]]
